name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-linux:
    name: Build Linux ProxyPass
    runs-on: ubuntu-24.04
    container:
      image: gcc:15
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apt-get update && apt-get install -y ninja-build cmake git openssl libssl-dev

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Upload Linux ProxyPass
        uses: actions/upload-artifact@v4
        with:
          name: ProxyPass-linux-x64
          path: bin/ProxyPass
